# Generated by Django 5.1.2 on 2024-10-15 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priceofferproduct',
            options={'verbose_name': 'Qiymət Təklifi Məhsulu', 'verbose_name_plural': 'Qiymət Təklifi Məhsulları'},
        ),
    ]
