# Generated by Django 5.1.2 on 2024-10-20 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0006_customer_feedback_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='feedback_checked',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='feedback_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='feedback_note',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='note_date',
        ),
        migrations.CreateModel(
            name='FeedbackNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_note', models.TextField(verbose_name='Geri dönüş qeydi')),
                ('feedback_date', models.DateField(verbose_name='Geri dönüş tarixi')),
                ('note_date', models.DateTimeField(auto_now_add=True, verbose_name='Qeyd tarixi')),
                ('feedback_checked', models.BooleanField(default=False, verbose_name='Geri dönüş yoxlanılması')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_notes', to='CRM.customer', verbose_name='Müştəri')),
            ],
            options={
                'verbose_name': 'Geri dönüş qeydi',
                'verbose_name_plural': 'Geri dönüş qeydləri',
                'ordering': ['-note_date'],
            },
        ),
    ]
