# Generated by Django 4.2.3 on 2024-10-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0007_remove_customer_feedback_checked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacknote',
            name='feedback_note',
            field=models.TextField(blank=True, null=True, verbose_name='Geri dönüş qeydi'),
        ),
    ]
