# Generated by Django 5.1.2 on 2024-10-21 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0009_customer_feedback_checked_customer_feedback_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='feedback_checked',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='feedback_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='feedback_note',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='note_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='products',
        ),
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_note', models.TextField(blank=True, null=True, verbose_name='Geri dönüş qeydi')),
                ('note_date', models.DateTimeField(auto_now_add=True, verbose_name='Qeyd tarixi')),
                ('feedback_date', models.DateField(blank=True, null=True, verbose_name='Geri dönüş tarixi')),
                ('feedback_checked', models.BooleanField(default=False, verbose_name='Geri dönüş yoxlanılması')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='CRM.customer', verbose_name='Müştəri')),
            ],
            options={
                'verbose_name': 'Müştəri Geri Dönüşü',
                'verbose_name_plural': 'Müştəri Geri Dönüşləri',
            },
        ),
    ]
