# Generated by Django 5.1.2 on 2024-10-21 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0011_customer_feedback_checked_customer_feedback_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='feedback_checked',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='feedback_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='feedback_note',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='note_date',
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_note', models.TextField(blank=True, null=True, verbose_name='Geri dönüş qeydi')),
                ('note_date', models.DateTimeField(auto_now=True, verbose_name='Qeyd tarixi')),
                ('feedback_date', models.DateField(blank=True, null=True, verbose_name='Geri dönüş tarixi')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='CRM.customer')),
            ],
            options={
                'verbose_name': 'Geri dönüş',
                'verbose_name_plural': 'Geri dönüşlər',
                'ordering': ['-note_date'],
            },
        ),
    ]
