# Generated by Django 5.1.2 on 2024-10-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0012_remove_customer_feedback_checked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='products',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='feedback_date',
        ),
        migrations.AddField(
            model_name='customer',
            name='feedback_date',
            field=models.DateField(blank=True, null=True, verbose_name='Geri dönüş tarixi'),
        ),
    ]
