# Generated by Django 5.1.2 on 2024-10-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0014_customer_feedback_checked_customer_feedback_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='feedback_checked_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Yoxlanma vaxtı'),
        ),
    ]
