# Generated by Django 5.1.2 on 2024-10-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0015_customer_feedback_checked_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='feedback_note',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='note_date',
        ),
        migrations.AddField(
            model_name='customer',
            name='feedback_notes',
            field=models.JSONField(default=list, verbose_name='Qeydlər və tarixlər'),
        ),
    ]
