# Generated by Django 5.1.2 on 2024-10-22 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0016_remove_customer_feedback_note_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='feedback_notes',
            new_name='feedback_note',
        ),
    ]
