# Generated by Django 5.1.2 on 2024-10-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0017_rename_feedback_notes_customer_feedback_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='feedback_note',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Qeydlər və tarixlər'),
        ),
    ]
