# Generated by Django 5.1.2 on 2024-10-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0018_alter_customer_feedback_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Məhsulun açıqlaması'),
        ),
    ]
